# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiVMS.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VMS(object):
    def setupUi(self, VMS):
        VMS.setObjectName("VMS")
        VMS.resize(800, 600)
        VMS.setMinimumSize(QtCore.QSize(800, 600))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 72, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 42, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 203, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 176, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 59, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 207, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 72, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 42, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 203, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 176, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 59, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 207, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 72, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 42, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 176, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 59, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 207, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        VMS.setPalette(palette)
        self.centralWidget = QtWidgets.QWidget(VMS)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralWidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setLineWidth(1)
        self.mainFrame.setMidLineWidth(0)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameMiddle = QtWidgets.QFrame(self.mainFrame)
        self.frameMiddle.setStyleSheet("background-color: transparent;")
        self.frameMiddle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameMiddle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMiddle.setLineWidth(1)
        self.frameMiddle.setObjectName("frameMiddle")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameMiddle)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameMenuBar = QtWidgets.QFrame(self.frameMiddle)
        self.frameMenuBar.setMinimumSize(QtCore.QSize(60, 0))
        self.frameMenuBar.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frameMenuBar.setStyleSheet("background-color: rgb(23,30,35)")
        self.frameMenuBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameMenuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMenuBar.setLineWidth(0)
        self.frameMenuBar.setObjectName("frameMenuBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameMenuBar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameToggle = QtWidgets.QFrame(self.frameMenuBar)
        self.frameToggle.setMinimumSize(QtCore.QSize(0, 50))
        self.frameToggle.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frameToggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameToggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToggle.setObjectName("frameToggle")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameToggle)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toggleBtnMenu = QtWidgets.QPushButton(self.frameToggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleBtnMenu.sizePolicy().hasHeightForWidth())
        self.toggleBtnMenu.setSizePolicy(sizePolicy)
        self.toggleBtnMenu.setStyleSheet("QPushButton {\n"
"    background-image:url(:/gui/icons/ic_menubar24.png);\n"
"    background-color: rgb(23,30,35);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(27, 42, 43);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(39,39,39);\n"
"}")
        self.toggleBtnMenu.setObjectName("toggleBtnMenu")
        self.verticalLayout_4.addWidget(self.toggleBtnMenu)
        self.verticalLayout_3.addWidget(self.frameToggle)
        self.frameBar = QtWidgets.QFrame(self.frameMenuBar)
        self.frameBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBar.setObjectName("frameBar")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameBar)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3.addWidget(self.frameBar)
        self.horizontalLayout_2.addWidget(self.frameMenuBar)
        self.frameContent = QtWidgets.QFrame(self.frameMiddle)
        self.frameContent.setStyleSheet("background-color: rgb(18,22,30)")
        self.frameContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameContent.setLineWidth(1)
        self.frameContent.setObjectName("frameContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameContent)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameViewer = QtWidgets.QFrame(self.frameContent)
        self.frameViewer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameViewer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameViewer.setObjectName("frameViewer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameViewer)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frameViewer)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageMain = QtWidgets.QWidget()
        self.pageMain.setStyleSheet("background: transparent;")
        self.pageMain.setObjectName("pageMain")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pageMain)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labelTitle = QtWidgets.QLabel(self.pageMain)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout_7.addWidget(self.labelTitle)
        self.labelReadme = QtWidgets.QLabel(self.pageMain)
        self.labelReadme.setMaximumSize(QtCore.QSize(16777215, 100))
        self.labelReadme.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelReadme.setObjectName("labelReadme")
        self.verticalLayout_7.addWidget(self.labelReadme)
        self.stackedWidget.addWidget(self.pageMain)
        self.pageViewerCams = QtWidgets.QWidget()
        self.pageViewerCams.setObjectName("pageViewerCams")
        self.stackedWidget.addWidget(self.pageViewerCams)
        self.pageOptions = QtWidgets.QWidget()
        self.pageOptions.setObjectName("pageOptions")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pageOptions)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.optListCams = QtWidgets.QFrame(self.pageOptions)
        self.optListCams.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.optListCams.setFrameShadow(QtWidgets.QFrame.Raised)
        self.optListCams.setObjectName("optListCams")
        self.gridLayout = QtWidgets.QGridLayout(self.optListCams)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonAddCam = QtWidgets.QPushButton(self.optListCams)
        self.buttonAddCam.setStyleSheet("QPushButton {\n"
"    color: rgb(230,230,230);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    padding: 10px;\n"
"    background-color: rgb(23,30,35);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(27, 42, 43);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(39,39,39);\n"
"}")
        self.buttonAddCam.setObjectName("buttonAddCam")
        self.gridLayout.addWidget(self.buttonAddCam, 0, 0, 1, 1)
        self.buttonDelCam = QtWidgets.QPushButton(self.optListCams)
        self.buttonDelCam.setStyleSheet("QPushButton {\n"
"    color: rgb(230,230,230);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    padding: 10px;\n"
"    background-color: rgb(23,30,35);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(27, 42, 43);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(39,39,39);\n"
"}")
        self.buttonDelCam.setObjectName("buttonDelCam")
        self.gridLayout.addWidget(self.buttonDelCam, 0, 1, 1, 1)
        self.buttonUpdCam = QtWidgets.QPushButton(self.optListCams)
        self.buttonUpdCam.setMaximumSize(QtCore.QSize(48, 16777215))
        self.buttonUpdCam.setStyleSheet("QPushButton {\n"
"    background-image: url(:/gui/icons/ic_upd24.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    padding: 10px;\n"
"    background-color: rgb(23,30,35);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(27, 42, 43);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(39,39,39);\n"
"}")
        self.buttonUpdCam.setIconSize(QtCore.QSize(24, 24))
        self.buttonUpdCam.setObjectName("buttonUpdCam")
        self.gridLayout.addWidget(self.buttonUpdCam, 0, 2, 1, 1)
        self.tableCamsWidget = QtWidgets.QTableWidget(self.optListCams)
        self.tableCamsWidget.setAutoFillBackground(False)
        self.tableCamsWidget.setStyleSheet("QTableWidget {    \n"
"    background-color: rgb(33,40,45);\n"
"    gridline-color: rgb(130,130,130);\n"
"    padding: 12px;\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"    color: rgb(230,230,230);\n"
"    border-color: rgb(230,230,230);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    Background-color: rgb(63, 70, 75);\n"
"    color: rgb(230,230,230);\n"
"}")
        self.tableCamsWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableCamsWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableCamsWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableCamsWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableCamsWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableCamsWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableCamsWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableCamsWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableCamsWidget.setShowGrid(True)
        self.tableCamsWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableCamsWidget.setRowCount(10)
        self.tableCamsWidget.setColumnCount(6)
        self.tableCamsWidget.setObjectName("tableCamsWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableCamsWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCamsWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCamsWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCamsWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCamsWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCamsWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCamsWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCamsWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCamsWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCamsWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCamsWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCamsWidget.setItem(0, 5, item)
        self.tableCamsWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableCamsWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableCamsWidget.horizontalHeader().setStretchLastSection(True)
        self.tableCamsWidget.verticalHeader().setVisible(False)
        self.tableCamsWidget.verticalHeader().setHighlightSections(False)
        self.tableCamsWidget.verticalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableCamsWidget, 1, 0, 1, 3)
        self.verticalLayout_8.addWidget(self.optListCams)
        self.stackedWidget.addWidget(self.pageOptions)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frameViewer)
        self.frameFooterBar = QtWidgets.QFrame(self.frameContent)
        self.frameFooterBar.setMinimumSize(QtCore.QSize(0, 20))
        self.frameFooterBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frameFooterBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frameFooterBar.setStyleSheet("background-color: rgb(33,40,45)")
        self.frameFooterBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameFooterBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFooterBar.setLineWidth(0)
        self.frameFooterBar.setObjectName("frameFooterBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameFooterBar)
        self.horizontalLayout_3.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.statusLabel = QtWidgets.QLabel(self.frameFooterBar)
        self.statusLabel.setStyleSheet("color: rgb(95, 100, 110);")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_3.addWidget(self.statusLabel)
        self.versionLabel = QtWidgets.QLabel(self.frameFooterBar)
        self.versionLabel.setStyleSheet("color: rgb(95, 100, 110);")
        self.versionLabel.setObjectName("versionLabel")
        self.horizontalLayout_3.addWidget(self.versionLabel, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frameFooterBar)
        self.horizontalLayout_2.addWidget(self.frameContent)
        self.frameContent.raise_()
        self.frameMenuBar.raise_()
        self.verticalLayout.addWidget(self.frameMiddle)
        self.horizontalLayout.addWidget(self.mainFrame)
        VMS.setCentralWidget(self.centralWidget)

        self.retranslateUi(VMS)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(VMS)

    def retranslateUi(self, VMS):
        _translate = QtCore.QCoreApplication.translate
        VMS.setWindowTitle(_translate("VMS", "Video Manager Studio"))
        self.labelTitle.setText(_translate("VMS", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#bebebe;\">Video Manager Studio </span></p><p align=\"center\"><span style=\" font-size:14pt; color:#797979;\">Classic 0.4</span></p><p align=\"center\"><br/></p></body></html>"))
        self.labelReadme.setText(_translate("VMS", "<html><head/><body><p align=\"center\"><span style=\" color:#cecece;\">Author</span><span style=\" font-weight:600; color:#cecece;\">: </span><span style=\" color:#cecece;\">Vladimir Novotorzhin</span><span style=\" font-weight:600; color:#cecece;\"><br/></span><a href=\"https://github.com/Sque-ak/Video-Manager-Studio-Classic\"><span style=\" text-decoration: underline; color:#2a7ace;\">GitHub</span></a></p></body></html>"))
        self.buttonAddCam.setText(_translate("VMS", "Add New Camera"))
        self.buttonDelCam.setText(_translate("VMS", "Delete Camera"))
        self.tableCamsWidget.setSortingEnabled(False)
        item = self.tableCamsWidget.horizontalHeaderItem(0)
        item.setText(_translate("VMS", "Name"))
        item = self.tableCamsWidget.horizontalHeaderItem(1)
        item.setText(_translate("VMS", "IP:Port/Url"))
        item = self.tableCamsWidget.horizontalHeaderItem(2)
        item.setText(_translate("VMS", "Login"))
        item = self.tableCamsWidget.horizontalHeaderItem(3)
        item.setText(_translate("VMS", "Password"))
        item = self.tableCamsWidget.horizontalHeaderItem(4)
        item.setText(_translate("VMS", "Type"))
        item = self.tableCamsWidget.horizontalHeaderItem(5)
        item.setText(_translate("VMS", "Status"))
        __sortingEnabled = self.tableCamsWidget.isSortingEnabled()
        self.tableCamsWidget.setSortingEnabled(False)
        item = self.tableCamsWidget.item(0, 0)
        item.setText(_translate("VMS", "Test"))
        item = self.tableCamsWidget.item(0, 1)
        item.setText(_translate("VMS", "RTSP:URL:544"))
        item = self.tableCamsWidget.item(0, 2)
        item.setText(_translate("VMS", "Login"))
        item = self.tableCamsWidget.item(0, 3)
        item.setText(_translate("VMS", "Password"))
        item = self.tableCamsWidget.item(0, 4)
        item.setText(_translate("VMS", "RTSP"))
        item = self.tableCamsWidget.item(0, 5)
        item.setText(_translate("VMS", "Disconnect"))
        self.tableCamsWidget.setSortingEnabled(__sortingEnabled)
        self.statusLabel.setText(_translate("VMS", "Hello, World!"))
        self.versionLabel.setText(_translate("VMS", "Version: Classic 0.4 Nov~"))
import res_guiVMS
